// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zycckfwngjlfxbmeaves.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Y2NrZnduZ2psZnhibWVhdmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjYyODksImV4cCI6MjA2NTY0MjI4OX0.a8yixbTRKIxK-mJzVmKKncIAE98uU0w0GxJowNphhz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);